### ISSUE TITLE
Non integer number of segments for the homosegmented GC-PC-SAFT 

### ISSUE THREAD

**Issue by LoGaL93** [feos-org/feos#183]
Hello,

In several works of your groups it appears that the number of segments of the homosegmented GC-PC-SAFT is relaxed to a continous variable to find target optimal molecules. 

I was looking at the documentation on how to assemble molecules from segments (python), and it seems to me that it is not possible? I see that you pass a list of strings defining the segments.

**Comment by prehner** [comment]
Hello, you are right with both of your observations! In molecular design studies that use FeOs (e.g., this one: [Neumaier et al. 2023](https://onlinelibrary.wiley.com/doi/full/10.1002/ente.202201403)), the PC-SAFT parameters are calculated outside of FeOs based on the sum rules by [Sauer et al. 2014](https://pubs.acs.org/doi/full/10.1021/ie502203w). Then these PC-SAFT parameters are used to instantiate the `EquationOfState` object.

At the moment, the reason for this is that the construction of PC-SAFT parameters from segment lists does some checks with respect to the applicability domain of the group-contribution method. Construction from (possibly non-integer) group counts could be included in FeOs but because of the simple workaround in Python was not a high priority so far.

**Comment by LoGaL93** [comment]
Makes sense, thanks a lot!
