### ISSUE TITLE
question about polar term in Heterosegmented gc-PCP-SAFT

### ISSUE THREAD

**Issue by longemen3000** [feos-org/feos#230]
Hello,

In sauer (2014) there is a mention of three different variations for the polar term in the case of heterosegmented gc-PCP-SAFT. Then, in Rehner (2023), for the Heterosegmented method and the database currently in the package, it is mentioned that there is a restriction on using just one polar group per component. Is this restriction intended to use the Homosegmented term (third variation) for the Heterosegmented GC method? If not, what is the current polar term implemented for hetero-gc-PCP-SAFT ?

**Comment by prehner** [comment]
Hi, thank you for the question, that can be a bit confusing, indeed. Sauer et al. conclude in their paper that the third variant is chosen, because it is "somewhat superior to the first and second variant". Therefore, this is the onyl variant that is implemented in FeOs. The restriction to one polar group was already set in place by Sauer et al. I would have to check what happens if someone were to instantiate gc-PC-SAFT with two or more polar groups in FeOs, but I wholeheartedly recommend to not do that, as the results would be all over the place.

In the new publication (Rehner 2023), we do not reinvestigate the polar term in gc-PC-SAFT; the focus is on the description of induced association and binary group-/group interaction parameters.

**Comment by longemen3000** [comment]
Thanks for the response!
