### ISSUE TITLE
"Hello world" example doesn't run

### ISSUE THREAD

**Issue by ianhbell** [feos-org/feos#66]
The main example in the README doesn't work:
```python
from feos.eos import EquationOfState, State
from feos.pcsaft import PcSaftParameters

# Build an equation of state
parameters = PcSaftParameters.from_json(['methanol'], 'parameters.json')
eos = EquationOfState.pcsaft(parameters)

# Define thermodynamic conditions
critical_point = State.critical_point(eos)

# Compute properties
p = critical_point.pressure()
t = critical_point.temperature
print(f'Critical point for methanol: T={t}, p={p}.')
```

I think because the path to ``"parameters.json"`` is invalid. Looking into the wheel, it looks like the parameter files are not provided with the wheel. Could you please include them with the wheel?

**Comment by ianhbell** [comment]
In teqp, I provide data files as package data, and a method to get the location of this folder, something similar in feos would be nice.

**Comment by g-bauer** [comment]
We provide parameter files in this GitHub repo [here](https://github.com/feos-org/feos/tree/main/parameters/pcsaft). Thanks for mentioning it though, we should make it more clear in the example that parameters have to be downloaded separately. 

For now, we have deliberately chosen to not provide a parameter data base, because for some substances there exists more than a single parameterization.
